### ISSUE TITLE
Image and Video upload

### ISSUE THREAD

**Issue by mkasajim** [haruiz/geminiplayground#23]
I have uploaded my file(s) in the my data section in the UI, but I don't have any idea how can I attach it to the message, like the one you showed. Please provide clear instruction.
Also, for convenience please add drag and drop to add file feature in the chat, or a add an attachment button in the chat message.

**Comment by haruiz** [comment]
Thanks for your feedback @mkasajim. We definitely are working on improving the documentation, that is in the roadmap. If you want to access the files from the UI, you just need to type `@`. Let me know if that works for you.
